version: '2.1'
services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    command: mongod --smallfiles

  api:
    container_name: api
    image: lehasvv2009/dnd-api # rename to build:api for custom build
    restart: on-failure
    links:
      - mongodb:mongodb
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb/test

  web:
    container_name: web
    image: lehasvv2009/dnd-web # rename to build:web for custom build
    restart: on-failure
    links:
      - api:api
    ports:
      - "80:80"

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower # automatically updates containers when new image is on docker hub
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: watchtower api --interval 30