# Spring app configurations
spring:
  data:
    mongodb.uri: mongodb://${MONGO_URL:localhost/test} # database uri
    rest:
      return-body-on-create: true # Return body when entity is created
      return-body-on-update: true # Return body when entity is updated